name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ../../api-composer/api.Dockerfile
            image_name: api-composer
          - context: ../../department-store/api.Dockerfile
            image_name: department-store
          - context: ../../job-position/api.Dockerfile
            image_name: job-position
          - context: ../../parking/api.Dockerfile
            image_name: parking

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.context }}/Dockerfile
        push: true
        tags: earthakkharawat/${{ matrix.image_name }}:latest
        platforms: linux/arm64
