apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-composer
  labels: 
    app: api-composer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-composer
  template:
    metadata:
      labels:
        app: api-composer
    spec:
      containers:
        - name: api-composer
          image: earthakkharawat/api-composer:latest
          env:
          - name: HOST_DEPARTMENT_STORE
            value: http://department-store:8000
          - name: HOST_JOB_POSITION
            value: http://job-position:8000
          - name: HOST_PARKING
            value: http://parking:8000
          ports:
            - containerPort: 8000
          
---
apiVersion: v1
kind: Service
metadata:
  name: api-composer
spec:
  selector:
    app: api-composer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  # type: NodePort
