apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: todo:release-3
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: NOTIFICATION_HOST
              value: "noti"
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  # type: NodePort
